### ISSUE TITLE
Compiling project on CentOs7

### ISSUE THREAD

**Issue by RefiPeretz** [Azure/mmlspark#590]
Hey I saw couple of issues on that subject. 
I know the project was written and compiled on ubuntu., but for the life of me I can't seem to compile it on CentOs.
I notice that some of you manage to compile it on centos and release some unofficial jars. I used some of them.

Could you please direct to a branch may or what are the steps to compile the project on centos?

**Comment by imatiach-msft** [comment]
hi @RefiPeretz , sorry about the trouble you are having.  The issue should be fixed in master, which uses the official lightgbm jars compiled on ubuntu 14.04 which doesn't seem to have some of the dependency issues.
You can get the master release from a private blob from any of the builds, eg the latest one is:

 --packages 
com.microsoft.ml.spark:mmlspark_2.11:0.17.dev23
and --repositories 
https://mmlspark.azureedge.net/maven

**Comment by RefiPeretz** [comment]
Hi @imatiach-msft . Evntually I managed to create Dockerfile from CentOs 7.6 where I can build the project. Maybe I can share it with you in the future if you want. I still have problems with libmpi_cxx altought I found a way around it. Thanks anyway.

**Comment by ranadeepsingh** [comment]
This build issue regarding CentOS 7 compilation was resolved in the thread via Docker containerization. The project build system has since migrated to standard sbt, and CentOS 7 has reached end-of-life and is no longer supported. This issue is now closed.
